# deploy static files

---

- name: init app www dir /srv/itranswarp-{{ timestamp }}/www
  file:
    path: /srv/itranswarp-{{ timestamp }}/www
    state: directory

- name: unarchive static files
  unarchive:
    src: ../release/resources.tar.gz
    dest: /srv/itranswarp-{{ timestamp }}/www
    owner: root
    group: root

- name: copy additional static files
  copy:
    src: environments/{{ profile }}/www
    dest: /srv/itranswarp-{{ timestamp }}
    owner: root
    group: root
