version: '3'

services:
  web:
      image: nginx:alpine
      container_name: itranswarp-web
      restart: always
      depends_on:
        - mysql
        - java
        - redis
      ports:
        - 0.0.0.0:80:80
        - 0.0.0.0:443:443
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../:/srv
        - ./nginx/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./nginx/log:/srv/itranswarp/log
        - ./nginx/ssl:/srv/itranswarp/ssl
      env_file:
        - ./.env 
      working_dir: /srv
      extra_hosts:
        - "local.itranswarp.com:${LOCAL_HOST}"
        - "source.local.itranswarp.com:${LOCAL_HOST}"
        - "static.local.itranswarp.com:${LOCAL_HOST}"
        - "www.local.itranswarp.com:${LOCAL_HOST}"
      networks:
        - dev
  java:
      image: itranswarp
      build:
        context: ../
        dockerfile: Dockerfile
      container_name: itranswarp-java
      depends_on:
        - mysql
        - redis
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../:/srv
      env_file:
        - ./.env 
      working_dir: /srv
      extra_hosts:
        - "local.itranswarp.com:${LOCAL_HOST}"
        - "source.local.itranswarp.com:${LOCAL_HOST}"
        - "static.local.itranswarp.com:${LOCAL_HOST}"
        - "www.local.itranswarp.com:${LOCAL_HOST}"
      networks:
        - dev
  redis:
      image: redis:5.0-alpine
      container_name: itranswarp-redis
      restart: always
      command: [--requirepass, "JFPRJ"]
      ports:
        - 0.0.0.0:16379:6379
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./redis:/data
  mysql:
      image: mysql:5.7
      container_name: itranswarp-mysql
      restart: always
      ports:
        - 0.0.0.0:13306:3306
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./mysql/data:/var/lib/mysql 
        - ./mysql/my.cnf:/etc/my.cnf
        - ./mysql/init:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      networks:
        - dev

networks:
  dev:
     driver: bridge
